services:
    server:
        image: '${APP_IMAGE:-animethemes-server-rust:local}'
        container_name: animethemes-server-rust
        command: ["start"]
        restart: unless-stopped
        ports:
            - "127.0.0.1:${APP_PORT:-5150}:${APP_PORT:-5150}"
        env_file: .env
        networks:
            - shared-network
        depends_on:
            redis:
                condition: service_healthy
    scheduler:
        image: '${APP_IMAGE:-animethemes-server-rust:local}'
        container_name: animethemes-server-rust-scheduler
        command: ["scheduler"]
        restart: unless-stopped
        env_file: .env
        networks:
            - shared-network
        depends_on:
            redis:
                condition: service_healthy
    worker:
        image: '${APP_IMAGE:-animethemes-server-rust:local}'
        container_name: animethemes-server-rust-worker
        command: ["start", "--worker"]
        restart: unless-stopped
        env_file: .env
        networks:
            - shared-network
        depends_on:
            redis:
                condition: service_healthy
    redis:
        image: 'redis:alpine'
        container_name: animethemes-server-rust-redis
        volumes:
            - 'redis-data:/data'
        networks:
            - shared-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    shared-network:
        external: true
volumes:
    redis-data: